### ISSUE TITLE
no such file 'models\\345M\\encoder.json' but I have encoder.json

### ISSUE THREAD

**Issue by GrahamboJangles** [openai/gpt-2#156]
Running generate_unconditional_samples.py outputs this error:

```python
Traceback (most recent call last):
  File "generate_unconditional_samples.py", line 78, in <module>
    fire.Fire(sample_model)
  File "A:\Coding_and_Scripting\Miniconda3\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "A:\Coding_and_Scripting\Miniconda3\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "A:\Coding_and_Scripting\Miniconda3\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "generate_unconditional_samples.py", line 43, in sample_model
    enc = encoder.get_encoder(model_name, models_dir)
  File "A:\Coding_and_Scripting\Miniconda3\_PROJECTS\gpt-2-master\src\encoder.py", line 109, in get_encoder
    with open(os.path.join(models_dir, model_name, 'encoder.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\345M\\encoder.json'
```
`interactive_conditional_sample.py` outputs the same error.

I even tried replacing `117M` in all the files with `345M` because I downloaded the 345M model. I also tried putting a direct path to replace line 109 in encoder.py:
 `with open(os.path.join(models_dir, model_name, 'encoder.json'), 'r') as f:`
I tried
`with open(os.path.join("A:\Coding_and_Scripting\Miniconda3\_PROJECTS\gpt-2-master\models\345M\encoder.json"), 'r') as f:`
and it gives me the error
```python
Traceback (most recent call last):
  File "interactive_conditional_samples.py", line 90, in <module>
    fire.Fire(interact_model)
  File "A:\Coding_and_Scripting\Miniconda3\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "A:\Coding_and_Scripting\Miniconda3\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "A:\Coding_and_Scripting\Miniconda3\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "interactive_conditional_samples.py", line 46, in interact_model
    enc = encoder.get_encoder(model_name, models_dir)
  File "A:\Coding_and_Scripting\Miniconda3\_PROJECTS\gpt-2-master\src\encoder.py", line 109, in get_encoder
    with open(os.path.join("A:\Coding_and_Scripting\Miniconda3\_PROJECTS\gpt-2-master\models\345M\encoder.json"), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'A:\\Coding_and_Scripting\\Miniconda3\\_PROJECTS\\gpt-2-master\\modelsåM\\encoder.json'
```
I don't know what's going on with the `modelsåM` at the last line there.

Thank you!

**Comment by GrahamboJangles** [comment]
I fixed this by changing the 12th line in `interactive_conditional_samples.py` from `117M` to `345M` and also running my console command from the master folder instead of the src folder.

**Comment by ghostxzxzgit** [comment]
This issue is caused due to the line 90 in src/interactive_conditional_samples.py : 
```python
if __name__ == '__main__':
    fire.Fire(interact_model)
```
By just passing the function object, the default arguments aren't passed to fire.
I fixed this by doing : 
```python
if __name__ == '__main__':
    fire.Fire(interact_model())
```
