### ISSUE TITLE
Docker installation does not work.

### ISSUE THREAD

**Issue by DAMO238** [openai/gpt-2#184]
I installed the Dockerfile.gpu version, at which I found that gpu passthrough is unavailable in Windows 10 Home, so I just changed the tensorflow version to the cpu version, and had to change to 1.13.1 in order to use the sort function as shown in this pull request: https://github.com/openai/gpt-2/pull/177

Now I get the following output:
```
root@56fc5edb1e15:/gpt-2# python3 src/generate_unconditional_samples.py --model_name 774M --nsamples 1
2019-09-21 16:50:49.057226: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-09-21 16:50:49.066466: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3696000000 Hz
2019-09-21 16:50:49.067238: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4a90030 executing computations on platform Host. Devices:
2019-09-21 16:50:49.067444: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /gpt-2/src/sample.py:64: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /gpt-2/src/sample.py:67: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.random.categorical instead.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-09-21 16:51:03.331001: W tensorflow/core/framework/allocator.cc:124] Allocation of 257315840 exceeds 10% of system memory.
Killed
```

As you can see, the program seems to get killed by something in the virtual environment. I am unsure what it is as I have not installed anything else in this environment.

**Comment by DAMO238** [comment]
This turns out to be a virtual memory bottleneck. To fix this, I closed docker terminal, opened virtualbox and stopped the default machine. I then changed the settings to give more cores and much more memory to the default machine. I then closed virtualbox and started up the docker terminal again, which reinitialized with the new settings. I also changed the Dockerfile.cpu to install 1.13.1 and built that one separately.

I gave about 11GB/16GB of ram to the vm and half of my cores to the vm

**Comment by alexellis** [comment]
I tried your example and got a different error:

```
root@750bbcc0d467:/gpt-2# python3 src/generate_unconditional_samples.py --model_name 124M --nsamples 1
2019-11-08 11:23:34.083457: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "src/generate_unconditional_samples.py", line 79, in <module>
    fire.Fire(sample_model)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "src/generate_unconditional_samples.py", line 62, in sample_model
    temperature=temperature, top_k=top_k, top_p=top_p
  File "/gpt-2/src/sample.py", line 74, in sample_sequence
    past, prev, output = body(None, context, context)
  File "/gpt-2/src/sample.py", line 66, in body
    logits = top_p_logits(logits, p=top_p)
  File "/gpt-2/src/sample.py", line 28, in top_p_logits
    sorted_logits = tf.sort(logits, direction='DESCENDING', axis=-1)
AttributeError: module 'tensorflow' has no attribute 'sort'
```

**Comment by IveJ** [comment]
Hi Issuer,

Check your CPU :

Your CPU supports instructions that this TensorFlow binary was not
compiled to use: AVX2 FMA

Or try install gpu if support or other support.

**Comment by alexellis** [comment]
No that wasn't the problem it's only a warning not an error. I found the solution in another issue and I will link it here in case anybody else wants it. 

The sort method now hangs off something like tf.contrib.framework.sort

**Comment by CarsonThompson** [comment]
@alexellis I am having this exact same issue, I would love that link!

**Comment by alexellis** [comment]
```
sed -ie s/sort\(/contrib\.framework\.sort\(/g src/sample.py 
```

**Comment by alexellis** [comment]
https://github.com/openai/gpt-2/issues/203#issuecomment-552080962

You're welcome 👍

**Comment by DAMO238** [comment]
The tensorflow.sort error comes from running the wrong version of tensorflow, you need to upgrade to 1.13.1 or higher to fix it. (Do that in the dockerfile) see pull request #177 to fix.

**Comment by valeross2019** [comment]
I need help:

PS D:\Users\NST\PythonProject\GPT-2_1\gpt-2-master\gpt-2> python src/generate_unconditional_samples.py | tee /tmp/samples
Traceback (most recent call last):
  File "src/generate_unconditional_samples.py", line 82, in <module>
    fire.Fire(sample_model)
  File "C:\Users\NST\AppData\Local\Programs\Python\Python35\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\NST\AppData\Local\Programs\Python\Python35\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Users\NST\AppData\Local\Programs\Python\Python35\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "src/generate_unconditional_samples.py", line 47, in sample_model
    enc = encoder.get_encoder(model_name, models_dir)
  File "D:\Users\NST\PythonProject\GPT-2_1\gpt-2-master\gpt-2\src\encoder.py", line 110, in get_encoder
    encoder = json.load(f)
  File "C:\Users\NST\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\NST\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\NST\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\NST\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
PS D:\Users\NST\PythonProject\GPT-2_1\gpt-2-master\gpt-2>

**Comment by valeross2019** [comment]
what am I doing wrong?
