### ISSUE TITLE
No such file or directory: 'models/774M/encoder.json

### ISSUE THREAD

**Issue by ywkl-writer** [openai/gpt-2#215]
I am using mac 10.15.1 
and I am using: src/generate_unconditional_samples.py

However, I have an error: FileNotFoundError: [Errno 2] No such file or directory: 'models/774M/encoder.json'

Checking in the model 774M folder I can see the file:
/Users/XXX/gpt-2/models/774M/encoder.json

Here the entire message
(tf1) XXX:~ XXX$ python3 ~/gpt-2/src/generate_unconditional_samples.py
Traceback (most recent call last):
  File "..../src/generate_unconditional_samples.py", line 79, in <module>
    fire.Fire(sample_model)
  File "/Applications/anaconda3/envs/tf1/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Applications/anaconda3/envs/tf1/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/Applications/anaconda3/envs/tf1/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "..../gpt-2/src/generate_unconditional_samples.py", line 44, in sample_model
    enc = encoder.get_encoder(model_name, models_dir)
  File "..../gpt-2/src/encoder.py", line 109, in get_encoder
    with open(os.path.join(models_dir, model_name, 'encoder.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/774M/encoder.json'

Any advise?
Thanks

**Comment by oxanderv** [comment]
hello how are you, I have the same problem, I also run the script on a mac machine, have you managed to solve it?
