### ISSUE TITLE
ModuleNotFoundError when training the model 

### ISSUE THREAD

**Issue by marloeshagens** [openai/gpt-2#238]
Hi guys, I am working on finetuning a GPT-2 in Google Collab to use in (behavioral) research, but I am very new to this and I don't understand what's going on. I have been using it without errors for a few weeks now, but now the algorithm does not cooperate with me anymore LOLz :) 

**Traceback (most recent call last):
  File "./train.py", line 14, in <module>
    import model, sample, encoder
  File "/content/gpt-2/src/model.py", line 3, in <module>
    from tensorflow.contrib.training import HParams
ModuleNotFoundError: No module named 'tensorflow.contrib'**

I've tried to import tensorflow.contrib manually (import tensorflow.contrib) but it does not solve the problem. Also, I have tried to see which tensorflow was installed, uninstalled and reinstalled newer versions but it still does not work.

Can someone please help me? Thanks so much. If needed, here is the google collab link: [](https://colab.research.google.com/drive/11g4-rPQ_GHrw7AOA85iROoZbJigvzRdO)

Cheers, 
Marloes

**Comment by TheUnkn0wnN00b** [comment]
I have this issue too. It's preventing me from using GPT-2 in my implementation whatsoever. Some sources show a solution as using Tensorflow 1.x, but this also doesn't seem to work.

**Comment by jochemstoel** [comment]
Getting the same error.

**Comment by Olegt0rr** [comment]
The same.

**Comment by marloeshagens** [comment]
Hi guys! I solved it for my code by the following, try to install the correct tensorflow version (if this does not work, first uninstall tensorflow)

```
!pip install tensorflow==1.15
!pip install tensorflow-gpu==1.15
!pip install 'tensorflow-estimator<1.15.0rc0,>=1.14.0rc0' --force-reinstall
```

I placed these lines of code before 
`!pip3 install -r requirements.txt`
and after installing the requirements
`from google.colab import files`

Hopefully it works for you guys! You can check out an example here: https://github.com/marloeshagens/GPT-2
or here as a notebook link: https://colab.research.google.com/gist/marloeshagens/4a0f72d6acd8a5bdd2d40a713497d280/dishonesty-updated-copy-of-gpt-2_medium_model.ipynb

**Comment by IveJ** [comment]
Thanks you all, Marl.

**Comment by jochemstoel** [comment]
As I work with GPT all the time doing inference and training I can't help but be curious for what behavioral research GPT is useful to you and how you use it. @marloeshagens

**Comment by marloeshagens** [comment]
Thanks for the interest! I trained GPT-2 on texts written by humans that give advice in a behavioral economic experiment. Eventually we will use these two different sources to see if there's any difference in the advice-taking, without using deception of who created the advice. If you are more interested, you can check out our Open Science Framework project page with all the preregistrations and some more explanations: https://osf.io/g3sw2/
