### ISSUE TITLE
got this error 

### ISSUE THREAD

**Issue by psdprasad** [openai/gpt-2#246]
~/gpt-2$ python3 src/interactive_conditional_samples.py
Traceback (most recent call last):
  File "src/interactive_conditional_samples.py", line 9, in <module>
    import model, sample, encoder
  File "/home/prasad/gpt-2/src/model.py", line 3, in <module>
    from tensorflow.contrib.training import HParams
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by skillor** [comment]
Sounds like an installation error to me: maybe this will help? https://github.com/openai/gpt-2/issues/236#issue-581076387

**Comment by HonayKing** [comment]
It should be a tensorflow version error! You can reinstall a tensorflow version with contrib module. Such as: tensorflow==1.12.0 or tensorflow-gpu==1.12.0 ...

**Comment by moona3k** [comment]
> Sounds like an installation error to me: maybe this will help? [#236 (comment)](https://github.com/openai/gpt-2/issues/236#issue-581076387)

Awesome, this fixed the issue :)
```
python3 -m pip install tensorflow==1.13.1
python3 -m pip install regex
```
