### ISSUE TITLE
Error with batch_size > 1

### ISSUE THREAD

**Issue by somsomers** [openai/gpt-2#281]
Hello.

Everything works fine until I increase nsamples and batch_size to >1. Tried in docker and in conda environment, with different versions of TF(from 1.12 to 1.15), on Tesla V100 and GF1060 - nothing helps.

```
Connected to pydev debugger (build 201.6668.115)
C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2021-02-13 02:10:21.495431: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\predoc\PycharmProjects\gpt2_2\gpt-2\sample.py:64: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 50257 and 2 for 'sample_sequence/Less' (op: 'Less') with input shapes: [2,50257], [2].
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "C:/Users/predoc/PycharmProjects/gpt2_2/gpt-2/interactive_conditional_samples.py", line 77, in interact_model
    temperature=temperature, top_k=top_k, top_p=top_p
  File "C:\Users\predoc\PycharmProjects\gpt2_2\gpt-2\sample.py", line 74, in sample_sequence
    past, prev, output = body(None, context, context)
  File "C:\Users\predoc\PycharmProjects\gpt2_2\gpt-2\sample.py", line 66, in body
    logits = top_p_logits(logits, p=top_p)
  File "C:\Users\predoc\PycharmProjects\gpt2_2\gpt-2\sample.py", line 37, in top_p_logits
    logits < min_values,
  File "C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4901, in less
    "Less", x=x, y=y, name=name)
  File "C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)
  File "C:\ProgramData\Anaconda3\envs\gpt2_2\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 50257 and 2 for 'sample_sequence/Less' (op: 'Less') with input shapes: [2,50257], [2].
```
Will be appreciate for any help. Thank you.

**Comment by aoyulong** [comment]
Try to add `min_values = min_values[:, tf.newaxis]`  after `min_values = tf.gather_nd(sorted_logits, indices)` in sample.py. This will meet the broadcast rule when do  `logits < min_values`  .

**Comment by somsomers** [comment]
Thank you! It solved the issue.
