### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by natemurthy** [openai/gpt-2#67]
I've reproduced this Python error 3 times already. First I tried out the unconditional samples:
```
$ python3 src/generate_unconditional_samples.py | tee samples

... TF log lines elided ...

======================================== SAMPLE 1 ========================================
Traceback (most recent call last):
  File "src/generate_unconditional_samples.py", line 55, in <module>
    fire.Fire(sample_model)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "src/generate_unconditional_samples.py", line 52, in sample_model
    print(text)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf8' in position 141: ordinal not in range(128)
```
That didn't work, but I got a few simple interactive conditional samples working until I entered this model prompt:
```
$ python3 src/interactive_conditional_samples.py --top_k 40

... TF log lines elided ...

================================================================================
Model prompt >>> Brexit has already cost the UK economy at least $80bn since the EU referendum,
======================================== SAMPLE 1 ========================================
Traceback (most recent call last):
  File "src/interactive_conditional_samples.py", line 68, in <module>
    fire.Fire(interact_model)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "src/interactive_conditional_samples.py", line 64, in interact_model
    print(text)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa3' in position 9: ordinal not in range(128)
```
Thought it didn't like the `$` or `,` characters so I removed those but still observed the same error:
```
$ python3 src/interactive_conditional_samples.py --top_k 40

... TF log lines elided ...

================================================================================
Model prompt >>> Brexit has already cost the UK economy at least 80bn since the EU referendum                                      
======================================== SAMPLE 1 ========================================
Traceback (most recent call last):
  File "src/interactive_conditional_samples.py", line 68, in <module>
    fire.Fire(interact_model)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.5/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "src/interactive_conditional_samples.py", line 64, in interact_model
    print(text)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 2400: ordinal not in range(128)
```
I'm running GPT-2 on `master` @ 99af6d7 in a container built from the `nvidia/cuda:9.0-runtime-ubuntu16.04` image running on a single core Nvidia Tesla T4 node provisioned with Google Kubernetes Engine.

**Comment by WuTheFWasThat** [comment]
ah ok, could you try with `export PYTHONIOENCODING=UTF-8`?

**Comment by natemurthy** [comment]
Closing this now that PR #69 is merged.
