### ISSUE TITLE
Problem with re.compile in encoder.py, Python 3.6+ x64

### ISSUE THREAD

**Issue by lostmsu** [openai/gpt-2#85]
This is from 9d1e704fec1726d5e051e98336b655ae8ce49242:
```python
re.compile(r"""'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+""")
```
When I try it in Python 3.6 or 3.7 x64 on either Windows or Ubuntu, I get 

```
>>> import re
>>> re.compile(r"""'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \p at position 26
```

Works fine in Python 2.7

**Comment by lostmsu** [comment]
This looks related:

> Unknown escapes consisting of '\\' and ASCII letter now raise a deprecation warning and will be forbidden in Python 3.6.

https://docs.python.org/3.5/library/re.html#re.sub

**Comment by lostmsu** [comment]
Even documentation for 2.7 does not list anything special for `\p`: https://docs.python.org/2/library/re.html

It seems to be an attempt to escape a Unicode character class, but I don't see any mention of that feature in either of `re`.

**Comment by lostmsu** [comment]
NVM, stupid me, did not notice regex in requirements.txt
