### ISSUE TITLE
json ecoder error

### ISSUE THREAD

**Issue by nachovoss** [openai/gpt-2#94]
Hey guys! thanks for this project.. still trying to make it run... 
A step by step guide would be useful.
Got this error when trying to run interactive_conditional_samples.py

User@DESKTOP-OR1I4MI MINGW64 ~/desktop/bots/gpt-2-master
$ python src/interactive_conditional_samples.py 117M
Traceback (most recent call last):
  File "src/interactive_conditional_samples.py", line 86, in <module>
    fire.Fire(interact_model)
  File "C:\Users\User\Desktop\bots\gpt-2-master\gptvenv\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Users\User\Desktop\bots\gpt-2-master\gptvenv\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Users\User\Desktop\bots\gpt-2-master\gptvenv\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "src/interactive_conditional_samples.py", line 42, in interact_model
    enc = encoder.get_encoder(model_name)
  File "C:\Users\User\desktop\bots\gpt-2-master\src\encoder.py", line 110, in get_encoder
    encoder = json.load(f)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(gptvenv)
User@DESKTOP-OR1I4MI MINGW64 ~/desktop/bots/gpt-2-master

help much appreciated

**Comment by WuTheFWasThat** [comment]
https://github.com/openai/gpt-2/blob/master/DEVELOPERS.md has a step by step guide, more or less.  it seems like your encoder.json file is empty maybe?  did you download it correctly?

**Comment by vmxeo** [comment]
Got the same error here as well, looks there's a problem during download script. 
All the files in the model contains this:
`<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to gpt-2/models/117m/encoder.json.</Details></Error>`

**Comment by vmxeo** [comment]
Doh, it's simpler than that. The name is case-sensitive. 117M is correct. 117m fails.
